name: pdp

services:
  # ---------------------
  # PostgreSQL Database
  # ---------------------
  postgres:
    container_name: pdp_postgres
    image: postgres:18
    #    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pdp_local
    ports:
      - "5432:5432"
    volumes:
      - pdp_db_data:/var/lib/postgresql
    networks:
      - pdp_network

  # ---------------------
  # Elasticsearch
  # ---------------------
  elasticsearch:
    container_name: pdp_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      xpack.security.http.ssl.enabled: "false"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - pdp_es_data:/usr/share/elasticsearch/data
    networks:
      - pdp_network

# ---------------------
# Networks
# ---------------------
networks:
  pdp_network:
    driver: bridge

# ---------------------
# Volumes
# ---------------------
volumes:
  pdp_db_data:
  pdp_es_data:
#  pdp_minio_data:
